### ISSUE TITLE
docs: usage documentation

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-jsonschemas#31]
TOC:
- [x] Purpose
  -  schema registry for invenio (primarily used by records) 
- [x] JSON Schema Basics
   - A quick example of a JSON Schema.
- [x] Configuration (in particular ``JSONSCHEMA_HOST``)
- [x] Registering JSON Schemas
- [x] Exposing JSON Schemas
   - ``/schemas/...`` (can be enabled/disabled per app)
- [x] Using/loading JSON Schemas
   - Explain how internally we don't make HTTP request to retrieve schemas.
- [x] Composable schemas with JSONRef
   - Explain how schemas can use JSONRef, and we can served fully rendered schemas (because some clients don't deal well with $refs).

Documentation could be linked to Invenio-Records that also have documentation on records and schemas.

Further:
- [x] Fix ReadTheDocs
- [ ] Remove experimental warning

**Comment by krzysztof** [comment]
Dependencies fix:

ext.py imports functools32 (see https://github.com/inveniosoftware/invenio-jsonschemas/blob/master/invenio_jsonschemas/ext.py#L43-L46)
```python
try:
    from functools import lru_cache
except ImportError:
    from functools32 import lru_cache
```

But it's not specified in the setup.py as python2.7 dependency like: https://github.com/inveniosoftware/invenio-collections/blob/4c5fd23a4c3fd24dec92f6215179f2098a684ee5/setup.py#L49-L51

**Comment by lnielsen** [comment]
Documentation:
- [ ] Fix ReadTheDocs
- [ ] JSON Schemas
- [ ] How to register schemas
- [ ] Efficient loading of schemas with JSONResolver
- [ ] Ref replacements
- [ ] URL endpoint for eschams
- [ ] Configuration: ``JSONSCHEMA_HOST``

- [ ] API documentation: explain json resolver.
