### ISSUE TITLE
views: resolving on-the-fly schema references

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio-jsonschemas#42]
Currently `invenio-jsonschemas` directly serves the schema from disk, without first resolving `$ref` to other schemas.

E.g.: see https://qa.inspirehep.net/schemas/records/hep.json which contains unresolved `$ref`s.

It would be actually great to resolve those and have a self-contained schema being served each time.

**Comment by kaplun** [comment]
Or at least this should be made configurable.

**Comment by jmartinm** [comment]
I can take care of this.
