### ISSUE TITLE
global: release checklist step 1-3

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-jsonschemas#68]
- Run [the release checklist](https://github.com/inveniosoftware/invenio/wiki/Release-preparation-checklist) step 1-3.
- E.g. remove GPLv2 and ``experimental`` note from the README.rst.

**Comment by krzysztof** [comment]
@lnielsen travis PyPI deploy username and password need to be updated

**Comment by lnielsen** [comment]
Yes, we'll update them all in one-go, since we also need an efficient way of changing the password in the future.
