### ISSUE TITLE
resolve_schema: allOf inside allOf is ignored

### ISSUE THREAD

**Issue by mesemus** [inveniosoftware/invenio-jsonschemas#85]
At https://github.com/inveniosoftware/invenio-jsonschemas/blob/master/invenio_jsonschemas/utils.py#L41-L47 allOf is popped from schema after parts of allOf are merged. If these parts contain another top-level allOf, it is ignored and its content is removed.

A fix might be:

    if 'allOf' in schema:
        all_of = schema.pop('allOf')
        for sub_schema in all_of:
            sub_schema.pop('title', None)
            sub_schema.pop('$id', None)
            schema = _merge_dicts(schema, sub_schema)
        schema = traverse(schema)

If you want, I can prepare a pull request.

**Comment by lnielsen** [comment]
Closed by #94  #92
